spring.application.name=kubernetesservice
server.port=6011
kubernetes.namespace=${KUBERNETES_NAMESPACE:msinit}
kubernetes.cicd.token=${KUBERNETES_CICD_TOKEN}
spring.servlet.multipart.max-file-size=1MB
