apiVersion: v1
kind: Service
metadata:
  name: gateway-redis
spec:
  clusterIP: None
  selector:
    app: gateway-redis
  ports:
    - port: 6379
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gateway-redis
spec:
  serviceName: gateway-redis
  replicas: 1
  selector:
    matchLabels:
      app: gateway-redis
  template:
    metadata:
      labels:
        app: gateway-redis
    spec:
      containers:
        - name: gateway-redis
          image: redis:7.4-alpine@sha256:ff02b58f971e7d7d156a1267e283fcbbeee91773b6aa36c49dac28ecfe28eadf
          command:
            - sh
            - -c
            - redis-server --appendonly yes --requirepass "$REDIS_PASSWORD"
          envFrom:
            - secretRef:
                name: gatewayservice-env
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: gateway-redis-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: gateway-redis-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
