apiVersion: v1
kind: Service
metadata:
  name: auth-redis
spec:
  clusterIP: None
  selector:
    app: auth-redis
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-redis
spec:
  serviceName: auth-redis
  replicas: 1
  selector:
    matchLabels:
      app: auth-redis
  template:
    metadata:
      labels:
        app: auth-redis
    spec:
      containers:
        - name: auth-redis
          image: redis:7.4-alpine@sha256:ff02b58f971e7d7d156a1267e283fcbbeee91773b6aa36c49dac28ecfe28eadf
          command:
            - sh
            - -c
            - redis-server --appendonly yes --requirepass "$AUTH_REDIS_PASSWORD"
          ports:
            - containerPort: 6379
          env:
            - name: AUTH_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authservice-env
                  key: AUTH_REDIS_PASSWORD
          volumeMounts:
            - name: auth-redis-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: auth-redis-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
